#!/usr/bin/python

import smbus

i2c = smbus.SMBus(1)

try:
  raw_data = i2c.read_word_data(0x69, 0x0a)
  formatted_data = format(raw_data,"02x")
  readable_output = (float(formatted_data) / 100)
except:
  readable_output = "error"

print readable_output
